SET FOREIGN_KEY_CHECKS = 0;
SET NAMES utf8mb4;
-- tian-gong DDL
CREATE DATABASE `tian-gong`
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;;
use `tian-gong`;
-- tian-gong.act_activity_redemption DDL
CREATE TABLE `tian-gong`.`act_activity_redemption` (`id` BIGINT NOT NULL AUTO_INCREMENT Comment "主键 ID",
`redemption_no` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "核销订单号 (唯一)",
`activity_id` BIGINT NOT NULL Comment "活动 ID",
`uid` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "用户 UID",
`deposit_id` BIGINT NOT NULL Comment "充值订单 ID",
`deposit_amount` DECIMAL(14,2) NOT NULL Comment "充值金额",
`bonus_amount` DECIMAL(14,2) NOT NULL DEFAULT 0.00 Comment "赠送金额",
`rewards` JSON NULL Comment "额外奖励发放记录",
`total_value` DECIMAL(14,2) NOT NULL DEFAULT 0.00 Comment "总奖励价值",
`status` TINYINT NOT NULL DEFAULT 0 Comment "状态 (0:待发放，1:已发放，2:发放失败)",
`fail_reason` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "失败原因",
`retry_count` TINYINT NULL DEFAULT 0 Comment "重试次数",
`paid_at` BIGINT NULL Comment "发放完成时间 (毫秒)",
`remark` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "备注",
`created_at` BIGINT NOT NULL Comment "创建时间 (毫秒)",
`updated_at` BIGINT NOT NULL Comment "更新时间 (毫秒)",
`is_deleted` TINYINT NOT NULL DEFAULT 0 Comment "软删除",
`created_by` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "创建人",
`updated_by` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "更新人",
INDEX `idx_activity_id`(`activity_id` ASC) USING BTREE,
INDEX `idx_created_at`(`created_at` ASC) USING BTREE,
INDEX `idx_status`(`status` ASC) USING BTREE,
INDEX `idx_user_id`(`uid` ASC) USING BTREE,
UNIQUE INDEX `uk_deposit_activity`(`deposit_id` ASC,`activity_id` ASC) USING BTREE,
UNIQUE INDEX `uk_redemption_no`(`redemption_no` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 3 ROW_FORMAT = Dynamic COMMENT = "活动核销记录表";
-- tian-gong.act_activity_stats_daily DDL
CREATE TABLE `tian-gong`.`act_activity_stats_daily` (`id` BIGINT NOT NULL AUTO_INCREMENT Comment "主键 ID",
`stat_date` DATE NOT NULL Comment "统计日期",
`activity_id` BIGINT NOT NULL Comment "活动 ID",
`activity_name` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "活动名称",
`participant_count` INT NOT NULL DEFAULT 0 Comment "参与人数",
`new_user_count` INT NOT NULL DEFAULT 0 Comment "新用户数",
`total_deposit` DECIMAL(14,2) NOT NULL DEFAULT 0.00 Comment "总充值金额",
`total_bonus` DECIMAL(14,2) NOT NULL DEFAULT 0.00 Comment "总赠送金额",
`tier_distribution` JSON NULL Comment "档位分布",
`roi` DECIMAL(10,4) NULL DEFAULT 0.0000 Comment "投资回报率",
`created_at` BIGINT NOT NULL Comment "创建时间 (毫秒)",
`updated_at` BIGINT NOT NULL Comment "更新时间 (毫秒)",
`is_deleted` TINYINT NOT NULL DEFAULT 0 Comment "软删除",
`created_by` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "创建人",
`updated_by` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "更新人",
INDEX `idx_activity_id`(`activity_id` ASC) USING BTREE,
INDEX `idx_stat_date`(`stat_date` ASC) USING BTREE,
UNIQUE INDEX `uk_date_activity`(`stat_date` ASC,`activity_id` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 2 ROW_FORMAT = Dynamic COMMENT = "活动每日统计表";
-- tian-gong.act_checkin_activity DDL
CREATE TABLE `tian-gong`.`act_checkin_activity` (`id` INT NOT NULL AUTO_INCREMENT Comment "ID",
`name` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "活动名称",
`description` VARCHAR(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "活动描述",
`start_time` BIGINT NOT NULL Comment "开始时间（毫秒）",
`end_time` BIGINT NOT NULL Comment "结束时间（毫秒）",
`cycle_days` INT NOT NULL DEFAULT 7 Comment "签到周期（天）",
`reward_rule` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "奖励规则（JSON）",
`status` TINYINT NOT NULL DEFAULT 1 Comment "状态（0-下架，1-上架）",
`create_time` BIGINT NOT NULL Comment "创建时间（毫秒）",
`update_time` BIGINT NOT NULL Comment "更新时间（毫秒）",
`is_deleted` TINYINT(1) NULL DEFAULT 0,
`created_at` BIGINT NULL,
`updated_at` BIGINT NULL,
`created_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
`updated_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
INDEX `idx_status_time`(`status` ASC,`start_time` ASC,`end_time` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 25 ROW_FORMAT = Dynamic COMMENT = "签到活动配置表";
-- tian-gong.act_checkin_base_reward DDL
CREATE TABLE `tian-gong`.`act_checkin_base_reward` (`id` BIGINT NOT NULL AUTO_INCREMENT Comment "主键 ID",
`day` INT NOT NULL Comment "第几天（1-30）",
`reward_amount` DECIMAL(10,2) NOT NULL Comment "基础奖励金额（分）",
`flow_requirement` DECIMAL(10,2) NULL DEFAULT 0.00 Comment "流水要求（元）",
`is_milestone` TINYINT NULL DEFAULT 0 Comment "是否里程碑",
`milestone_name` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "里程碑名称",
`enabled` TINYINT NULL DEFAULT 1 Comment "是否启用",
`sort_order` INT NULL DEFAULT 0 Comment "排序",
`created_at` BIGINT NOT NULL Comment "创建时间",
`updated_at` BIGINT NOT NULL Comment "更新时间",
`is_deleted` TINYINT(1) NULL DEFAULT 0,
`created_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
`updated_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
INDEX `idx_enabled`(`enabled` ASC) USING BTREE,
UNIQUE INDEX `uk_day`(`day` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 31 ROW_FORMAT = Dynamic COMMENT = "签到基础奖励配置表";
-- tian-gong.act_checkin_config DDL
CREATE TABLE `tian-gong`.`act_checkin_config` (`config_key` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "配置键",
`config_value` VARCHAR(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "配置值",
`config_type` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT 'string' Comment "配置类型：string/number/boolean/json",
`description` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "配置描述",
`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(0) Comment "更新时间",
INDEX `idx_key`(`config_key` ASC) USING BTREE,
PRIMARY KEY (`config_key`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic COMMENT = "签到全局配置表";
-- tian-gong.act_checkin_continuous_reward DDL
CREATE TABLE `tian-gong`.`act_checkin_continuous_reward` (`id` BIGINT NOT NULL AUTO_INCREMENT Comment "主键 ID",
`day` INT NOT NULL Comment "第几天（1-30）",
`reward_amount` DECIMAL(10,2) NOT NULL Comment "连续奖励金额（分）",
`flow_requirement` DECIMAL(10,2) NULL DEFAULT 0.00 Comment "流水要求（元）",
`enabled` TINYINT NULL DEFAULT 1 Comment "是否启用",
`sort_order` INT NULL DEFAULT 0 Comment "排序",
`created_at` BIGINT NOT NULL Comment "创建时间",
`updated_at` BIGINT NOT NULL Comment "更新时间",
`is_deleted` TINYINT(1) NULL DEFAULT 0,
`created_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
`updated_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
INDEX `idx_enabled`(`enabled` ASC) USING BTREE,
UNIQUE INDEX `uk_day`(`day` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 10 ROW_FORMAT = Dynamic COMMENT = "签到连续奖励配置表";
-- tian-gong.act_deposit_activity DDL
CREATE TABLE `tian-gong`.`act_deposit_activity` (`id` BIGINT NOT NULL AUTO_INCREMENT Comment "主键 ID",
`activity_code` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "活动编码 (唯一标识)",
`activity_name` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "活动名称",
`activity_type` TINYINT NOT NULL Comment "活动类型 (1:首充，2:档位，3:限时)",
`start_time` BIGINT NOT NULL Comment "开始时间 (毫秒)",
`end_time` BIGINT NOT NULL Comment "结束时间 (毫秒)",
`rules` JSON NOT NULL Comment "活动规则配置",
`rewards` JSON NOT NULL Comment "奖励配置",
`participant_limit` INT NULL DEFAULT 0 Comment "参与人数上限 (0-无限制)",
`daily_limit` INT NULL DEFAULT 0 Comment "每日参与次数上限 (0-无限制)",
`total_limit` INT NULL DEFAULT 0 Comment "总参与次数上限 (0-无限制)",
`min_amount` DECIMAL(12,2) NULL DEFAULT 0.00 Comment "最低充值金额",
`max_bonus` DECIMAL(12,2) NULL DEFAULT 0.00 Comment "最高赠送金额",
`eligible_users` TINYINT NULL DEFAULT 1 Comment "参与用户类型 (1:全部，2:新用户，3:VIP+)",
`status` TINYINT NOT NULL DEFAULT 0 Comment "状态 (0:草稿，1:进行中，2:已结束)",
`sort_order` INT NOT NULL DEFAULT 0 Comment "排序",
`remark` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "备注",
`created_at` BIGINT NOT NULL Comment "创建时间 (毫秒)",
`updated_at` BIGINT NOT NULL Comment "更新时间 (毫秒)",
`is_deleted` TINYINT NOT NULL DEFAULT 0 Comment "软删除",
`created_by` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "创建人",
`updated_by` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "更新人",
INDEX `idx_activity_type`(`activity_type` ASC) USING BTREE,
INDEX `idx_status`(`status` ASC) USING BTREE,
INDEX `idx_time`(`start_time` ASC,`end_time` ASC) USING BTREE,
UNIQUE INDEX `uk_activity_code`(`activity_code` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 6 ROW_FORMAT = Dynamic COMMENT = "充值活动配置表";
-- tian-gong.act_deposit_tier DDL
CREATE TABLE `tian-gong`.`act_deposit_tier` (`id` BIGINT NOT NULL AUTO_INCREMENT Comment "主键 ID",
`activity_id` BIGINT NOT NULL Comment "活动 ID (0-通用档位)",
`tier_name` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "档位名称",
`amount` DECIMAL(12,2) NOT NULL Comment "充值金额",
`min_amount` DECIMAL(12,2) NULL Comment "金额范围最小值 (用于阶梯)",
`max_amount` DECIMAL(12,2) NULL Comment "金额范围最大值 (用于阶梯)",
`bonus_rate` DECIMAL(5,4) NOT NULL DEFAULT 0.0000 Comment "赠送比例 (0-1)",
`bonus_amount` DECIMAL(12,2) NULL DEFAULT 0.00 Comment "固定赠送金额 (优先级高于比例)",
`rewards` JSON NULL Comment "额外奖励配置",
`badge` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "标识 (热门/超值/至尊)",
`sort_order` INT NOT NULL DEFAULT 0 Comment "排序",
`status` TINYINT NOT NULL DEFAULT 1 Comment "状态 (1:启用，0:禁用)",
`created_at` BIGINT NOT NULL Comment "创建时间 (毫秒)",
`updated_at` BIGINT NOT NULL Comment "更新时间 (毫秒)",
`is_deleted` TINYINT NOT NULL DEFAULT 0 Comment "软删除",
`created_by` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "创建人",
`updated_by` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "更新人",
INDEX `idx_activity_id`(`activity_id` ASC) USING BTREE,
INDEX `idx_amount`(`amount` ASC) USING BTREE,
INDEX `idx_status`(`status` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 7 ROW_FORMAT = Dynamic COMMENT = "充值档位配置表";
-- tian-gong.act_first_deposit_record DDL
CREATE TABLE `tian-gong`.`act_first_deposit_record` (`id` BIGINT NOT NULL AUTO_INCREMENT Comment "主键 ID",
`uid` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "用户 UID",
`deposit_id` BIGINT NOT NULL Comment "充值订单 ID",
`deposit_amount` DECIMAL(14,2) NOT NULL Comment "充值金额",
`bonus_amount` DECIMAL(14,2) NOT NULL DEFAULT 0.00 Comment "赠送金额",
`bonus_rate` DECIMAL(5,4) NOT NULL DEFAULT 0.0000 Comment "赠送比例",
`tier_level` TINYINT NULL Comment "档位等级 (1/2/3 档)",
`status` TINYINT NOT NULL DEFAULT 1 Comment "状态 (1:成功，2:失败)",
`fail_reason` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "失败原因",
`paid_at` BIGINT NULL Comment "发放完成时间 (毫秒)",
`remark` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "备注",
`created_at` BIGINT NOT NULL Comment "创建时间 (毫秒)",
`updated_at` BIGINT NOT NULL Comment "更新时间 (毫秒)",
`is_deleted` TINYINT NOT NULL DEFAULT 0 Comment "软删除",
`created_by` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "创建人",
`updated_by` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "更新人",
INDEX `idx_created_at`(`created_at` ASC) USING BTREE,
UNIQUE INDEX `uk_deposit_id`(`deposit_id` ASC) USING BTREE,
UNIQUE INDEX `uk_user_id`(`uid` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 5 ROW_FORMAT = Dynamic COMMENT = "首充记录表";
-- tian-gong.act_user_checkin DDL
CREATE TABLE `tian-gong`.`act_user_checkin` (`id` INT NOT NULL AUTO_INCREMENT Comment "ID",
`uid` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "用户 ID",
`activity_id` BIGINT NULL,
`checkin_date` INT NOT NULL Comment "签到日期（YYYYMMDD）",
`checkin_time` BIGINT NOT NULL Comment "签到时间（毫秒）",
`reward_amount` DECIMAL(20,2) NOT NULL DEFAULT 0.00 Comment "获得奖励金额",
`consecutive_days` INT NOT NULL DEFAULT 1 Comment "连续签到天数",
`is_compensate` TINYINT NULL DEFAULT 0 Comment "是否补签：0-否，1-是",
`total_days` INT NULL DEFAULT 1 Comment "累计签到天数",
`flow_completed` DECIMAL(10,2) NULL DEFAULT 0.00 Comment "当日已完成流水（元）",
`base_reward` DECIMAL(10,2) NULL DEFAULT 0.00 Comment "基础奖励金额（分）",
`continuous_reward` DECIMAL(10,2) NULL DEFAULT 0.00 Comment "连续奖励金额（分）",
`create_time` BIGINT NULL,
`is_deleted` TINYINT(1) NULL DEFAULT 0,
`created_at` BIGINT NULL,
`updated_at` BIGINT NULL,
`created_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
`updated_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
INDEX `idx_checkin_date`(`checkin_date` ASC) USING BTREE,
INDEX `idx_uid_checkin_date`(`uid` ASC,`checkin_date` ASC) USING BTREE,
UNIQUE INDEX `uk_uid_activity_date`(`uid` ASC,`activity_id` ASC,`checkin_date` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 27 ROW_FORMAT = Dynamic COMMENT = "用户签到记录表";
-- tian-gong.act_user_compensate_card DDL
CREATE TABLE `tian-gong`.`act_user_compensate_card` (`id` BIGINT NOT NULL AUTO_INCREMENT Comment "主键 ID",
`uid` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "用户 UID",
`card_count` INT NULL DEFAULT 0 Comment "可用补签卡数量",
`monthly_limit` INT NULL DEFAULT 5 Comment "每月使用上限",
`used_this_month` INT NULL DEFAULT 0 Comment "本月已使用数量",
`reset_date` DATE NOT NULL Comment "重置日期（每月 1 号）",
`first_checkin_time` BIGINT NULL Comment "首次签到时间（毫秒）",
`created_at` BIGINT NOT NULL Comment "创建时间",
`updated_at` BIGINT NOT NULL Comment "更新时间",
`created_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
`updated_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
`is_deleted` TINYINT(1) NULL DEFAULT 0,
INDEX `idx_reset_date`(`reset_date` ASC) USING BTREE,
UNIQUE INDEX `uk_uid`(`uid` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 92 ROW_FORMAT = Dynamic COMMENT = "用户补签卡表";
-- tian-gong.adm_admin_user DDL
CREATE TABLE `tian-gong`.`adm_admin_user` (`id` BIGINT NOT NULL AUTO_INCREMENT,
`username` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "用户名",
`password` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "密码",
`role` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT 'ADMIN' Comment "角色",
`status` INT NULL DEFAULT 1 Comment "状态",
`is_deleted` TINYINT(1) NULL DEFAULT 0,
`created_at` BIGINT NULL,
`updated_at` BIGINT NULL,
`created_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
`updated_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
`nickname` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 239 ROW_FORMAT = Dynamic COMMENT = "管理员表";
-- tian-gong.adm_permission DDL
CREATE TABLE `tian-gong`.`adm_permission` (`id` BIGINT NOT NULL AUTO_INCREMENT,
`code` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "权限编码",
`name` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "权限名称",
`resource_type` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "资源类型",
`description` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "描述",
`status` INT NULL DEFAULT 1 Comment "状态：0-禁用，1-启用",
`is_deleted` TINYINT NULL DEFAULT 0 Comment "逻辑删除",
`created_at` BIGINT NULL,
`updated_at` BIGINT NULL,
`created_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
`updated_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 97 ROW_FORMAT = Dynamic COMMENT = "权限表";
-- tian-gong.adm_role DDL
CREATE TABLE `tian-gong`.`adm_role` (`id` BIGINT NOT NULL AUTO_INCREMENT,
`code` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "角色编码",
`name` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "角色名称",
`description` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "描述",
`status` INT NULL DEFAULT 1 Comment "状态：0-禁用，1-启用",
`is_deleted` TINYINT NULL DEFAULT 0 Comment "逻辑删除",
`created_at` BIGINT NULL,
`updated_at` BIGINT NULL,
`created_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
`updated_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 18 ROW_FORMAT = Dynamic COMMENT = "角色表";
-- tian-gong.adm_role_permission DDL
CREATE TABLE `tian-gong`.`adm_role_permission` (`id` BIGINT NOT NULL AUTO_INCREMENT,
`role_id` BIGINT NOT NULL Comment "角色 ID",
`permission_id` BIGINT NOT NULL Comment "权限 ID",
`is_deleted` TINYINT(1) NULL DEFAULT 0,
`created_at` BIGINT NULL,
`updated_at` BIGINT NULL,
`created_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
`updated_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
INDEX `idx_permission_id`(`permission_id` ASC) USING BTREE,
INDEX `idx_role_id`(`role_id` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 52 ROW_FORMAT = Dynamic COMMENT = "角色权限关联表";
-- tian-gong.adm_vip_adjust_log DDL
CREATE TABLE `tian-gong`.`adm_vip_adjust_log` (`id` BIGINT NOT NULL AUTO_INCREMENT Comment "主键 ID",
`uid` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "用户 ID",
`old_level` TINYINT NULL Comment "原 VIP 等级",
`new_level` TINYINT NULL Comment "新 VIP 等级",
`adjust_type` TINYINT NOT NULL DEFAULT 1 Comment "调整类型 (1 升级 2 降级 3 重置)",
`reason` VARCHAR(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "调整原因",
`status` TINYINT NOT NULL DEFAULT 1 Comment "状态 (1 待审批 2 已通过 3 已拒绝)",
`operator_id` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "操作人 ID",
`operator_name` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "操作人姓名",
`approver_id` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "审批人 ID",
`approver_name` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "审批人姓名",
`approve_time` BIGINT NULL Comment "审批时间（毫秒）",
`approve_remark` VARCHAR(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "审批备注",
`created_at` BIGINT NOT NULL Comment "创建时间（毫秒）",
`updated_at` BIGINT NOT NULL Comment "更新时间（毫秒）",
`is_deleted` TINYINT(1) NULL DEFAULT 0,
INDEX `idx_created_at`(`created_at` ASC) USING BTREE,
INDEX `idx_operator_id`(`operator_id` ASC) USING BTREE,
INDEX `idx_status`(`status` ASC) USING BTREE,
INDEX `idx_uid`(`uid` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 1 ROW_FORMAT = Dynamic COMMENT = "VIP 调整日志表";
-- tian-gong.admin_user DDL
CREATE TABLE `tian-gong`.`admin_user` (`id` BIGINT NOT NULL AUTO_INCREMENT Comment "管理员 ID",
`username` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "用户名",
`password` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "密码（加密存储）",
`email` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "邮箱",
`phone` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "手机号",
`avatar` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "头像 URL",
`role` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT 'admin' Comment "角色（admin/operator/auditor）",
`status` TINYINT(1) NULL DEFAULT 1 Comment "状态（1: 启用，0: 禁用）",
`created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP Comment "创建时间",
`updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP(0) Comment "更新时间",
`last_login_at` DATETIME NULL Comment "最后登录时间",
`deleted` TINYINT(1) NULL DEFAULT 0 Comment "是否删除",
UNIQUE INDEX `uk_username`(`username` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 5 ROW_FORMAT = Dynamic COMMENT = "管理员用户表";
-- tian-gong.gam_balance_transfer DDL
CREATE TABLE `tian-gong`.`gam_balance_transfer` (`id` BIGINT NOT NULL AUTO_INCREMENT,
`uid` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "用户 ID",
`provider_code` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "厂商简写：JILI/PG/PP",
`vendor_id` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "服务商 ID：HG_JILI",
`game_id` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "游戏 ID",
`transaction_id` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "转账交易 ID",
`transfer_type` INT NOT NULL Comment "1-转入厂商，2-转回平台",
`amount` DECIMAL(16,4) NOT NULL Comment "转账金额",
`balance_before` DECIMAL(16,4) NOT NULL Comment "转账前余额",
`balance_after` DECIMAL(16,4) NOT NULL Comment "转账后余额",
`vendor_balance` DECIMAL(16,4) NULL Comment "厂商侧余额",
`status` INT NOT NULL DEFAULT 0 Comment "0-处理中，1-成功，2-失败",
`error_message` VARCHAR(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "错误信息",
`retry_count` INT NULL DEFAULT 0 Comment "重试次数",
`created_at` BIGINT NOT NULL,
`updated_at` BIGINT NOT NULL,
`created_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
`updated_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
`is_deleted` TINYINT(1) NULL DEFAULT 0,
INDEX `idx_created_at`(`created_at` ASC) USING BTREE,
INDEX `idx_uid_provider`(`uid` ASC,`provider_code` ASC) USING BTREE,
INDEX `idx_vendor_id`(`vendor_id` ASC) USING BTREE,
UNIQUE INDEX `uk_transaction_id`(`transaction_id` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 20 ROW_FORMAT = Dynamic COMMENT = "游戏余额转账记录";
-- tian-gong.gam_game DDL
CREATE TABLE `tian-gong`.`gam_game` (`id` BIGINT NOT NULL AUTO_INCREMENT,
`gid` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "游戏 ID",
`name` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "游戏名称",
`provider` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "厂商",
`vendor_id` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "服务商ID",
`status` INT NULL DEFAULT 0 Comment "状态：0-下架，1-上架，2-维护",
`is_valid_flow` TINYINT NULL DEFAULT 0 Comment "是否有效流水游戏：0-否，1-是",
`provider_gid` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "厂商对应的游戏ID",
`sort` INT NULL DEFAULT 9999 Comment "排序权重",
`is_deleted` TINYINT(1) NULL DEFAULT 0,
`icon` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
`type` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
`created_at` BIGINT NULL,
`updated_at` BIGINT NULL,
`created_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
`updated_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
`rtp` DECIMAL(19,4) NULL,
`is_hot` TINYINT(1) NULL,
`is_new` TINYINT(1) NULL,
INDEX `idx_manuf`(`provider` ASC) USING BTREE,
INDEX `idx_valid_flow`(`is_valid_flow` ASC) USING BTREE,
UNIQUE INDEX `uk_gid`(`gid` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 958 ROW_FORMAT = Dynamic COMMENT = "游戏表";
-- tian-gong.gam_game_provider DDL
CREATE TABLE `tian-gong`.`gam_game_provider` (`id` BIGINT NOT NULL AUTO_INCREMENT,
`provider_id` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "厂商ID",
`name` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "厂商名称",
`game_count` INT NULL DEFAULT 0 Comment "游戏数量",
`status` INT NULL DEFAULT 1 Comment "状态：0-禁用，1-启用",
`create_time` BIGINT NULL Comment "创建时间(毫秒)",
`current_vendor_id` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
`icon` VARCHAR(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "厂商图标",
`sort` INT NULL,
`is_deleted` TINYINT(1) NULL DEFAULT 0,
`created_at` BIGINT NULL,
`updated_at` BIGINT NULL,
`created_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
`updated_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
UNIQUE INDEX `provider_id`(`provider_id` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 12 ROW_FORMAT = Dynamic COMMENT = "游戏厂商表";
-- tian-gong.gam_game_vendor DDL
CREATE TABLE `tian-gong`.`gam_game_vendor` (`id` BIGINT NOT NULL AUTO_INCREMENT,
`provider_id` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "厂商ID",
`vendor_id` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "服务商ID",
`vendor_name` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "服务商名称",
`commission_rate` DECIMAL(5,4) NULL DEFAULT 0.0000 Comment "抽佣比例(0.0000-1.0000)",
`api_key` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "API密钥",
`api_secret` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "API密钥私钥",
`api_url` VARCHAR(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "API地址",
`status` INT NULL DEFAULT 1 Comment "状态：0-禁用，1-启用",
`create_time` BIGINT NULL Comment "创建时间(毫秒)",
`account` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "账号",
`is_deleted` TINYINT(1) NULL DEFAULT 0,
`created_at` BIGINT NULL,
`updated_at` BIGINT NULL,
`created_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
`updated_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
`data_feed_url` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
INDEX `idx_provider_id`(`provider_id` ASC) USING BTREE,
INDEX `idx_vendor_id`(`vendor_id` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 16 ROW_FORMAT = Dynamic COMMENT = "游戏服务商表";
-- tian-gong.gam_user_game_favorite DDL
CREATE TABLE `tian-gong`.`gam_user_game_favorite` (`id` BIGINT NOT NULL AUTO_INCREMENT Comment "主键ID",
`uid` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL Comment "用户UID",
`game_id` BIGINT NOT NULL Comment "游戏ID",
`gid` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "游戏代码",
`status` INT NOT NULL DEFAULT 1 Comment "状态：0-取消收藏，1-收藏",
`created_at` BIGINT NOT NULL Comment "创建时间（毫秒）",
`updated_at` BIGINT NOT NULL Comment "更新时间（毫秒）",
`deleted` INT NOT NULL DEFAULT 0 Comment "逻辑删除：0-未删除，1-已删除",
INDEX `idx_created_at`(`created_at` ASC) USING BTREE,
INDEX `idx_game_id`(`game_id` ASC) USING BTREE,
INDEX `idx_status`(`status` ASC) USING BTREE,
INDEX `idx_uid`(`uid` ASC) USING BTREE,
UNIQUE INDEX `uk_uid_game_id`(`uid` ASC,`game_id` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci AUTO_INCREMENT = 1 ROW_FORMAT = Dynamic COMMENT = "用户游戏收藏表";
-- tian-gong.gam_user_session DDL
CREATE TABLE `tian-gong`.`gam_user_session` (`id` BIGINT NOT NULL AUTO_INCREMENT,
`uid` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "用户 ID",
`provider_code` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "厂商简写",
`vendor_id` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "服务商 ID",
`game_id` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "游戏 ID",
`session_token` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "会话 token",
`vendor_balance` DECIMAL(16,4) NULL DEFAULT 0.0000 Comment "厂商侧余额",
`status` INT NOT NULL DEFAULT 1 Comment "1-游戏中，0-已结束",
`started_at` BIGINT NOT NULL,
`ended_at` BIGINT NULL,
`created_at` BIGINT NOT NULL,
`updated_at` BIGINT NOT NULL,
`created_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
`updated_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
`is_deleted` TINYINT(1) NULL DEFAULT 0,
INDEX `idx_started_at`(`started_at` ASC) USING BTREE,
INDEX `idx_uid_status`(`uid` ASC,`status` ASC) USING BTREE,
UNIQUE INDEX `uk_session_token`(`session_token` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 14 ROW_FORMAT = Dynamic COMMENT = "用户游戏会话";
-- tian-gong.msg_message DDL
CREATE TABLE `tian-gong`.`msg_message` (`id` BIGINT NOT NULL AUTO_INCREMENT,
`title` VARCHAR(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "消息标题",
`content` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "消息内容",
`type` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "类型：system/bonus/promo",
`is_read` INT NULL DEFAULT 0 Comment "是否已读：0-未读，1-已读",
`action_type` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "操作类型：claim/redirect",
`action_link` VARCHAR(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "操作链接",
`create_time` BIGINT NULL Comment "创建时间(毫秒)",
`is_deleted` TINYINT(1) NULL DEFAULT 0,
`created_at` BIGINT NULL,
`updated_at` BIGINT NULL,
`created_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
`updated_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
`uid` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "用户 UID",
INDEX `idx_uid`(`uid` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 1345 ROW_FORMAT = Dynamic COMMENT = "消息表";
-- tian-gong.pay_balance_adjustment DDL
CREATE TABLE `tian-gong`.`pay_balance_adjustment` (`id` BIGINT NOT NULL AUTO_INCREMENT Comment "调账记录ID",
`uid` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL Comment "用户UID",
`amount` DECIMAL(20,8) NOT NULL Comment "调整金额",
`flow_multiple` DECIMAL(10,2) NOT NULL DEFAULT 0.00 Comment "流水倍数",
`flow_amount` DECIMAL(20,8) NULL Comment "流水金额",
`reason` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL Comment "调整原因",
`status` INT NOT NULL DEFAULT 0 Comment "状态",
`applicant_id` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL Comment "申请人ID",
`applicant_name` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL Comment "申请人名称",
`approver_id` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL Comment "审批人ID",
`approver_name` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL Comment "审批人名称",
`approve_time` BIGINT NULL Comment "审批时间",
`reject_reason` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL Comment "拒绝原因",
`before_balance` DECIMAL(20,8) NULL Comment "调整前余额",
`after_balance` DECIMAL(20,8) NULL Comment "调整后余额",
`client_ip` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL Comment "客户端IP",
`created_at` BIGINT NOT NULL Comment "创建时间",
`updated_at` BIGINT NOT NULL Comment "更新时间",
`is_deleted` TINYINT(1) NULL DEFAULT 0,
`created_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
`updated_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
INDEX `idx_applicant_id`(`applicant_id` ASC) USING BTREE,
INDEX `idx_created_at`(`created_at` ASC) USING BTREE,
INDEX `idx_status`(`status` ASC) USING BTREE,
INDEX `idx_uid`(`uid` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci AUTO_INCREMENT = 16 ROW_FORMAT = Dynamic COMMENT = "调账记录表";
-- tian-gong.pay_bank_channel_config DDL
CREATE TABLE `tian-gong`.`pay_bank_channel_config` (`id` BIGINT NOT NULL AUTO_INCREMENT Comment "主键ID",
`code` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL Comment "渠道代码（如GCASH、PAYMAYA、BANK等）",
`name` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL Comment "显示名称",
`icon_url` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "图标URL",
`type` INT NOT NULL DEFAULT 3 Comment "类型：1-充值，2-提现，3-双向",
`sort_order` INT NULL DEFAULT 0 Comment "排序权重",
`status` INT NULL DEFAULT 1 Comment "状态：0-禁用，1-启用",
`description` VARCHAR(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "描述信息",
`is_deleted` TINYINT NULL DEFAULT 0 Comment "逻辑删除：0-未删除，1-已删除",
`created_at` BIGINT NOT NULL Comment "创建时间（毫秒）",
`updated_at` BIGINT NOT NULL Comment "更新时间（毫秒）",
`created_by` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "创建人",
`updated_by` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "更新人",
INDEX `idx_status`(`status` ASC) USING BTREE,
INDEX `idx_type`(`type` ASC) USING BTREE,
UNIQUE INDEX `uk_code`(`code` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci AUTO_INCREMENT = 1 ROW_FORMAT = Dynamic COMMENT = "银行渠道配置表";
-- tian-gong.pay_channel DDL
CREATE TABLE `tian-gong`.`pay_channel` (`id` BIGINT NOT NULL AUTO_INCREMENT Comment "渠道商ID",
`channel_code` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL Comment "渠道代码",
`channel_name` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL Comment "渠道名称",
`status` TINYINT NOT NULL DEFAULT 1 Comment "状态：0-禁用 1-启用",
`created_at` BIGINT NOT NULL Comment "创建时间",
`updated_at` BIGINT NOT NULL Comment "更新时间",
`created_by` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL Comment "创建人",
`updated_by` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL Comment "更新人",
`is_deleted` TINYINT NOT NULL DEFAULT 0 Comment "是否删除：0-否 1-是",
`type` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL,
UNIQUE INDEX `uk_channel_code`(`channel_code` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci AUTO_INCREMENT = 4 ROW_FORMAT = Dynamic COMMENT = "渠道商表";
-- tian-gong.pay_channel_account DDL
CREATE TABLE `tian-gong`.`pay_channel_account` (`id` BIGINT NOT NULL AUTO_INCREMENT Comment "渠道账号ID",
`channel_id` BIGINT NOT NULL Comment "渠道商ID",
`merchant_code` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL Comment "商户代码(渠道给我们的商户号)",
`merchant_name` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL Comment "商户名称",
`app_id` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL Comment "应用ID",
`public_key` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL Comment "公钥(AES加密)",
`private_key` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL Comment "私钥(AES加密)",
`status` TINYINT NOT NULL DEFAULT 1 Comment "状态：0-禁用 1-启用",
`created_at` BIGINT NOT NULL Comment "创建时间",
`updated_at` BIGINT NOT NULL Comment "更新时间",
`created_by` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL Comment "创建人",
`updated_by` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL Comment "更新人",
`is_deleted` TINYINT NOT NULL DEFAULT 0 Comment "是否删除：0-否 1-是",
`balance` DECIMAL(12,2) NOT NULL DEFAULT 0.00 Comment "余额",
`domain` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL Comment "域名",
`code` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL Comment "渠道账号编码",
`name` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL Comment "渠道账号名称",
INDEX `idx_channel_id`(`channel_id` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci AUTO_INCREMENT = 4 ROW_FORMAT = Dynamic COMMENT = "渠道账号表";
-- tian-gong.pay_limit DDL
CREATE TABLE `tian-gong`.`pay_limit` (`id` BIGINT NOT NULL AUTO_INCREMENT Comment "限额配置ID",
`channel_account_id` BIGINT NOT NULL Comment "渠道账号ID",
`type` TINYINT NOT NULL Comment "类型：1-充值 2-提现",
`method` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL Comment "支付方式代码",
`min_amount` DECIMAL(15,2) NOT NULL DEFAULT 0.00 Comment "最小金额",
`max_amount` DECIMAL(15,2) NOT NULL DEFAULT 0.00 Comment "最大金额",
`created_at` BIGINT NOT NULL Comment "创建时间",
`updated_at` BIGINT NOT NULL Comment "更新时间",
`created_by` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL Comment "创建人",
`updated_by` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL Comment "更新人",
`is_deleted` TINYINT NOT NULL DEFAULT 0 Comment "是否删除：0-否 1-是",
`sort` INT NULL DEFAULT 0 Comment "排序值，数值越小越靠前",
INDEX `idx_channel_account_id`(`channel_account_id` ASC) USING BTREE,
INDEX `idx_type_method`(`type` ASC,`method` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci AUTO_INCREMENT = 10 ROW_FORMAT = Dynamic COMMENT = "限额配置表";
-- tian-gong.pay_recharge DDL
CREATE TABLE `tian-gong`.`pay_recharge` (`id` BIGINT NOT NULL AUTO_INCREMENT,
`order_no` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "订单号",
`uid` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "用户 UID",
`amount` DECIMAL(20,2) NOT NULL Comment "充值金额",
`status` INT NULL DEFAULT 0 Comment "状态：0-待支付，1-成功，2-取消，3-超时",
`method` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "产品名称",
`channel_account_id` BIGINT NULL Comment "渠道账号ID",
`is_deleted` TINYINT(1) NULL DEFAULT 0,
`created_at` BIGINT NULL,
`updated_at` BIGINT NULL,
`created_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
`updated_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
`completed_at` BIGINT NULL Comment "完成时间",
`exception_reason` VARCHAR(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
`flow_multiple` DECIMAL(19,4) NULL,
`activity_bonus` DECIMAL(19,4) NULL,
INDEX `idx_channel_account_id`(`channel_account_id` ASC) USING BTREE,
INDEX `idx_status`(`status` ASC) USING BTREE,
UNIQUE INDEX `uk_order_no`(`order_no` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 124 ROW_FORMAT = Dynamic COMMENT = "充值表";
-- tian-gong.pay_withdraw DDL
CREATE TABLE `tian-gong`.`pay_withdraw` (`id` BIGINT NOT NULL AUTO_INCREMENT,
`order_no` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "订单号",
`uid` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "用户 UID",
`amount` DECIMAL(20,2) NOT NULL Comment "提现金额",
`status` INT NULL DEFAULT 0 Comment "状态：0-待审核，1-通过，2-处理中，3-完成，4-拒绝",
`channel_account_id` BIGINT NULL Comment "渠道账号ID",
`account` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "收款账户",
`account_type` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "账户类型",
`account_name` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "账户姓名",
`channel` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "提现渠道",
`method` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "产品名称",
`is_deleted` TINYINT(1) NULL DEFAULT 0,
`created_at` BIGINT NULL,
`updated_at` BIGINT NULL,
`created_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
`updated_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
`fail_reason` VARCHAR(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "渠道失败原因",
`completed_at` BIGINT NULL,
`accept_account` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "收款账号",
`fee_amount` DECIMAL(19,4) NULL,
`actual_amount` DECIMAL(19,4) NULL,
`bank_code` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
`bank_name` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
`reject_reason` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
`flow_check_status` TINYINT(1) NULL,
`risk_check_status` TINYINT(1) NULL,
INDEX `idx_channel_account_id`(`channel_account_id` ASC) USING BTREE,
INDEX `idx_status`(`status` ASC) USING BTREE,
UNIQUE INDEX `uk_order_no`(`order_no` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 20 ROW_FORMAT = Dynamic COMMENT = "提现表";
-- tian-gong.promo_code DDL
CREATE TABLE `tian-gong`.`promo_code` (`id` BIGINT NOT NULL AUTO_INCREMENT Comment "主键 ID",
`code` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "兑换码字符串",
`type` VARCHAR(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "SINGLE=单码, BATCH=批量码",
`batch_id` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "批次ID，批量码使用",
`status` VARCHAR(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'ACTIVE' Comment "ACTIVE/DISABLED/EXPIRED",
`reward_type` VARCHAR(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'BALANCE' Comment "奖励类型，当前仅BALANCE",
`reward_amount` DECIMAL(12,2) NOT NULL Comment "奖励金额",
`total_limit` INT NULL Comment "总使用次数上限，NULL=不限（仅单码有效）",
`used_count` INT NOT NULL DEFAULT 0 Comment "已使用次数",
`target_type` VARCHAR(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'ALL' Comment "ALL/NEW_USER/VIP_LEVEL/WHITELIST",
`new_user_days` INT NULL Comment "新用户天数限制",
`min_vip_level` INT NULL Comment "最低VIP等级要求",
`expired_at` BIGINT NULL Comment "过期时间（毫秒），NULL=永不过期",
`remark` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "备注",
`created_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "创建人（管理员）",
`created_at` BIGINT NOT NULL Comment "创建时间（毫秒）",
`updated_at` BIGINT NOT NULL Comment "更新时间（毫秒）",
`is_deleted` TINYINT NOT NULL DEFAULT 0 Comment "软删除",
`updated_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
INDEX `idx_batch_id`(`batch_id` ASC) USING BTREE,
INDEX `idx_created_at`(`created_at` ASC) USING BTREE,
INDEX `idx_status`(`status` ASC) USING BTREE,
INDEX `idx_type`(`type` ASC) USING BTREE,
UNIQUE INDEX `uk_code`(`code` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 18 ROW_FORMAT = Dynamic COMMENT = "兑换码主表";
-- tian-gong.promo_code_record DDL
CREATE TABLE `tian-gong`.`promo_code_record` (`id` BIGINT NOT NULL AUTO_INCREMENT Comment "主键 ID",
`code_id` BIGINT NOT NULL Comment "关联 promo_code.id",
`code` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "冗余码字符串，便于查询",
`uid` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "使用用户uid",
`reward_amount` DECIMAL(12,2) NOT NULL Comment "实际到账金额",
`used_at` BIGINT NOT NULL Comment "使用时间（毫秒）",
INDEX `idx_code_id`(`code_id` ASC) USING BTREE,
INDEX `idx_uid`(`uid` ASC) USING BTREE,
INDEX `idx_used_at`(`used_at` ASC) USING BTREE,
UNIQUE INDEX `uk_code_uid`(`code_id` ASC,`uid` ASC) USING BTREE comment "防止同一用户重复使用同一码",
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 1 ROW_FORMAT = Dynamic COMMENT = "兑换码使用记录表";
-- tian-gong.promo_code_whitelist DDL
CREATE TABLE `tian-gong`.`promo_code_whitelist` (`id` BIGINT NOT NULL AUTO_INCREMENT Comment "主键 ID",
`code_id` BIGINT NOT NULL Comment "关联 promo_code.id",
`uid` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "白名单用户uid",
INDEX `idx_code_id`(`code_id` ASC) USING BTREE,
UNIQUE INDEX `uk_code_uid`(`code_id` ASC,`uid` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 1 ROW_FORMAT = Dynamic COMMENT = "兑换码白名单表";
-- tian-gong.rsk_alert DDL
CREATE TABLE `tian-gong`.`rsk_alert` (`id` BIGINT NOT NULL AUTO_INCREMENT Comment "主键 ID",
`alert_type` TINYINT NULL Comment "预警类型（1-充值异常，2-提现异常，3-投注异常，4-账户异常，5-登录异常）",
`alert_level` TINYINT NULL Comment "预警等级（1-提示，2-警告，3-高危，4-紧急）",
`uid` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "用户 UID",
`alert_title` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "预警标题",
`alert_content` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "预警内容",
`alert_data` JSON NULL Comment "预警详细数据（JSON）",
`related_event_type` TINYINT NULL Comment "关联事件类型",
`related_event_id` INT NULL Comment "关联事件 ID",
`related_order_no` VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "关联订单号",
`notify_status` TINYINT NULL DEFAULT 0 Comment "通知状态（0-未通知，1-已通知）",
`notify_channel` TINYINT NULL Comment "通知渠道（1-站内，2-邮件，3-短信）",
`notify_time` BIGINT NULL Comment "通知时间",
`handle_status` TINYINT NULL DEFAULT 0 Comment "处理状态（0-待处理，1-已处理，2-已忽略，3-已升级）",
`handler_uid` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "处理人 UID",
`handle_time` BIGINT NULL Comment "处理时间",
`handle_remark` VARCHAR(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "处理备注",
`is_deleted` TINYINT(1) NULL DEFAULT 0 Comment "逻辑删除",
`created_at` BIGINT NULL Comment "创建时间",
`updated_at` BIGINT NULL Comment "更新时间",
`created_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "创建人",
`updated_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "更新人",
INDEX `idx_alert_level`(`alert_level` ASC) USING BTREE,
INDEX `idx_created_at`(`created_at` ASC) USING BTREE,
INDEX `idx_handle_status`(`handle_status` ASC) USING BTREE,
INDEX `idx_uid`(`uid` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci AUTO_INCREMENT = 1 ROW_FORMAT = Dynamic COMMENT = "风险预警表";
-- tian-gong.rsk_blacklist DDL
CREATE TABLE `tian-gong`.`rsk_blacklist` (`id` BIGINT NOT NULL AUTO_INCREMENT Comment "主键 ID",
`blacklist_type` TINYINT NULL Comment "黑名单类型（1-用户，2-IP，3-设备，4-银行卡，5-收款账户）",
`blacklist_value` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "黑名单值（UID/IP/设备ID等）",
`blacklist_reason` VARCHAR(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "加入原因",
`source_type` TINYINT NULL Comment "来源类型（1-系统自动，2-人工添加）",
`risk_event_id` INT NULL Comment "关联风控事件 ID",
`expire_type` TINYINT NULL Comment "过期类型（1-永久，2-临时）",
`expire_time` BIGINT NULL Comment "过期时间（临时黑名单）",
`status` TINYINT NULL DEFAULT 1 Comment "状态（0-禁用，1-启用）",
`added_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "添加人 UID",
`removed_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "移除人 UID",
`removed_at` BIGINT NULL Comment "移除时间",
`remove_reason` VARCHAR(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "移除原因",
`is_deleted` TINYINT(1) NULL DEFAULT 0 Comment "逻辑删除",
`created_at` BIGINT NULL Comment "创建时间",
`updated_at` BIGINT NULL Comment "更新时间",
`created_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "创建人",
`updated_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "更新人",
`risk_alert_id` INT NULL,
INDEX `idx_blacklist_type_value`(`blacklist_type` ASC,`blacklist_value` ASC) USING BTREE,
INDEX `idx_created_at`(`created_at` ASC) USING BTREE,
INDEX `idx_expire_time`(`expire_time` ASC) USING BTREE,
INDEX `idx_status`(`status` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci AUTO_INCREMENT = 1 ROW_FORMAT = Dynamic COMMENT = "风控黑名单表";
-- tian-gong.rsk_control_rule DDL
CREATE TABLE `tian-gong`.`rsk_control_rule` (`id` INT NOT NULL AUTO_INCREMENT Comment "规则ID",
`rule_name` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "规则名称",
`rule_type` INT NULL Comment "规则类型：1-流水要求，2-大额预警，3-频次限制，4-异常检测",
`rule_config` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "规则配置（JSON）",
`status` INT NULL DEFAULT 0 Comment "状态：0-禁用，1-启用",
`is_deleted` TINYINT(1) NULL DEFAULT 0 Comment "是否删除",
`created_at` BIGINT NULL Comment "创建时间（毫秒）",
`updated_at` BIGINT NULL Comment "修改时间（毫秒）",
`created_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "创建人",
`updated_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "修改人",
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci AUTO_INCREMENT = 1 ROW_FORMAT = Dynamic COMMENT = "风控规则配置表";
-- tian-gong.rsk_event DDL
CREATE TABLE `tian-gong`.`rsk_event` (`id` INT NOT NULL AUTO_INCREMENT Comment "事件 ID",
`uid` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "平台用户 ID",
`event_type` INT NOT NULL Comment "事件类型：1-充值后快速提现，2-流水不足，3-异常下注，4-多设备登录，5-无游戏直接提现，6-频繁交易",
`event_level` INT NOT NULL DEFAULT 1 Comment "事件等级：1-提示，2-警告，3-高危",
`event_data` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "事件数据（JSON）",
`handle_status` INT NOT NULL DEFAULT 0 Comment "处理状态：0-待处理，1-已处理，2-已忽略",
`handle_remark` VARCHAR(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "处理备注",
`handler_uid` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "处理人 UID",
`create_time` BIGINT NOT NULL Comment "创建时间（毫秒）",
`is_deleted` TINYINT(1) NULL DEFAULT 0,
`created_at` BIGINT NULL,
`updated_at` BIGINT NULL,
`created_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
`updated_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
INDEX `idx_create_time`(`create_time` ASC) USING BTREE,
INDEX `idx_event_type`(`event_type` ASC) USING BTREE,
INDEX `idx_handle_status`(`handle_status` ASC) USING BTREE,
INDEX `idx_uid`(`uid` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 1 ROW_FORMAT = Dynamic COMMENT = "风控事件记录表";
-- tian-gong.rsk_user_profile DDL
CREATE TABLE `tian-gong`.`rsk_user_profile` (`id` BIGINT NOT NULL AUTO_INCREMENT Comment "主键 ID",
`uid` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "用户 UID",
`risk_score` INT NULL DEFAULT 0 Comment "风险评分（0-100）",
`risk_level` TINYINT NULL DEFAULT 0 Comment "风险等级（0-正常，1-低风险，2-中风险，3-高风险）",
`total_recharge_count` INT NULL DEFAULT 0 Comment "累计充值次数",
`total_withdraw_count` INT NULL DEFAULT 0 Comment "累计提现次数",
`total_bet_count` INT NULL DEFAULT 0 Comment "累计投注次数",
`avg_recharge_amount` DECIMAL(18,2) NULL Comment "平均充值金额",
`avg_withdraw_amount` DECIMAL(18,2) NULL Comment "平均提现金额",
`max_single_recharge` DECIMAL(18,2) NULL Comment "单笔最大充值",
`max_single_withdraw` DECIMAL(18,2) NULL Comment "单笔最大提现",
`recharge_withdraw_ratio` DECIMAL(10,4) NULL Comment "充提比例",
`bet_win_ratio` DECIMAL(10,4) NULL Comment "投注盈亏比",
`last_recharge_time` BIGINT NULL Comment "最后充值时间",
`last_withdraw_time` BIGINT NULL Comment "最后提现时间",
`last_bet_time` BIGINT NULL Comment "最后投注时间",
`new_withdraw_after_deposit` INT NULL DEFAULT 0 Comment "充后快速提现次数",
`no_play_withdraw_count` INT NULL DEFAULT 0 Comment "无游戏直接提现次数",
`multi_device_login_count` INT NULL DEFAULT 0 Comment "多设备登录次数",
`frequent_transaction_count` INT NULL DEFAULT 0 Comment "频繁交易次数",
`abnormal_bet_count` INT NULL DEFAULT 0 Comment "异常投注次数",
`risk_tags` JSON NULL Comment "风险标签列表（JSON）",
`manual_review_status` TINYINT NULL DEFAULT 0 Comment "人工审核状态（0-无，1-待审核，2-已审核）",
`reviewer_uid` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "审核人 UID",
`review_remark` VARCHAR(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "审核备注",
`last_risk_check_time` BIGINT NULL Comment "最后风控检查时间",
`is_deleted` TINYINT(1) NULL DEFAULT 0 Comment "逻辑删除",
`created_at` BIGINT NULL Comment "创建时间",
`updated_at` BIGINT NULL Comment "更新时间",
`created_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "创建人",
`updated_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "更新人",
INDEX `idx_last_risk_check_time`(`last_risk_check_time` ASC) USING BTREE,
INDEX `idx_risk_level`(`risk_level` ASC) USING BTREE,
INDEX `idx_risk_score`(`risk_score` ASC) USING BTREE,
UNIQUE INDEX `uk_uid`(`uid` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci AUTO_INCREMENT = 1 ROW_FORMAT = Dynamic COMMENT = "用户风险画像表";
-- tian-gong.sys_banner DDL
CREATE TABLE `tian-gong`.`sys_banner` (`id` BIGINT NOT NULL AUTO_INCREMENT,
`image` VARCHAR(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "Banner图片URL",
`title` VARCHAR(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "标题",
`description` VARCHAR(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "描述",
`cta` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "按钮文本",
`cta_link` VARCHAR(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "按钮跳转链接",
`badge` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "标签",
`badge_color` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "标签颜色",
`sort_order` INT NULL DEFAULT 0 Comment "排序顺序",
`status` INT NULL DEFAULT 1 Comment "状态：0-禁用，1-启用",
`start_time` BIGINT NULL Comment "开始时间(毫秒)",
`end_time` BIGINT NULL Comment "结束时间(毫秒)",
`create_time` BIGINT NULL Comment "创建时间(毫秒)",
`modify_time` BIGINT NULL Comment "修改时间(毫秒)",
`is_deleted` TINYINT(1) NULL DEFAULT 0,
`created_at` BIGINT NULL,
`updated_at` BIGINT NULL,
`created_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
`updated_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
`link_type` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'NONE' Comment "跳转类型：NONE/EXTERNAL/INTERNAL",
`position` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'HOME' Comment "展示位置：HOME/LOGIN/ACTIVITY",
INDEX `idx_position_status`(`position` ASC,`status` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 7 ROW_FORMAT = Dynamic COMMENT = "Banner轮播图表";
-- tian-gong.sys_config DDL
CREATE TABLE `tian-gong`.`sys_config` (`id` BIGINT NOT NULL AUTO_INCREMENT,
`config_key` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
`config_value` VARCHAR(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
`description` VARCHAR(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
`created_at` BIGINT NULL,
`updated_at` BIGINT NULL,
`is_deleted` TINYINT(1) NULL DEFAULT 0,
`created_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
`updated_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
UNIQUE INDEX `config_key`(`config_key` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci AUTO_INCREMENT = 8 ROW_FORMAT = Dynamic;
-- tian-gong.sys_manuf_reconciliation_daily DDL
CREATE TABLE `tian-gong`.`sys_manuf_reconciliation_daily` (`id` INT NOT NULL AUTO_INCREMENT Comment "主键ID",
`stat_date` DATE NOT NULL Comment "统计日期",
`manuf` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL Comment "厂商标识",
`total_bet` DECIMAL(18,2) NULL DEFAULT 0.00 Comment "总下注金额",
`total_win` DECIMAL(18,2) NULL DEFAULT 0.00 Comment "总派奖金额",
`total_pnl` DECIMAL(18,2) NULL DEFAULT 0.00 Comment "平台盈亏",
`total_rebate` DECIMAL(18,2) NULL DEFAULT 0.00 Comment "总返点金额",
`record_count` INT NULL DEFAULT 0 Comment "记录数",
`reconcile_status` INT NULL DEFAULT 0 Comment "对账状态：0-待对账，1-已对账，2-差异",
`diff_amount` DECIMAL(18,2) NULL DEFAULT 0.00 Comment "差异金额",
`diff_remark` VARCHAR(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "差异备注",
`created_at` BIGINT NOT NULL Comment "创建时间（毫秒）",
`updated_at` BIGINT NOT NULL Comment "更新时间（毫秒）",
`is_deleted` INT NULL DEFAULT 0 Comment "逻辑删除：0-未删除，1-已删除",
INDEX `idx_manuf`(`manuf` ASC) USING BTREE,
INDEX `idx_reconcile_status`(`reconcile_status` ASC) USING BTREE,
INDEX `idx_stat_date`(`stat_date` ASC) USING BTREE,
UNIQUE INDEX `uk_date_manuf`(`stat_date` ASC,`manuf` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci AUTO_INCREMENT = 1 ROW_FORMAT = Dynamic COMMENT = "厂商对账日报表";
-- tian-gong.sys_operation_log DDL
CREATE TABLE `tian-gong`.`sys_operation_log` (`id` BIGINT NOT NULL AUTO_INCREMENT Comment "主键 ID",
`module` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "业务模块：CHECKIN/GAME/PAYMENT/USER...",
`operation_type` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "操作类型：CREATE/UPDATE/DELETE/GRANT/REVOKE...",
`biz_id` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "业务 ID（如配置 ID、用户 UID 等）",
`biz_key` VARCHAR(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "业务键（如 day_7、uid_xxx）",
`old_value` JSON NULL Comment "变更前值（JSON）",
`new_value` JSON NOT NULL Comment "变更后值（JSON）",
`operator` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "操作人（管理员账号）",
`operate_time` BIGINT NOT NULL Comment "操作时间（毫秒）",
`operate_ip` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "操作 IP",
`remark` VARCHAR(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "备注",
`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP Comment "创建时间",
INDEX `idx_module`(`module` ASC) USING BTREE,
INDEX `idx_operate_time`(`operate_time` ASC) USING BTREE,
INDEX `idx_operation_type`(`operation_type` ASC) USING BTREE,
INDEX `idx_operator`(`operator` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 159 ROW_FORMAT = Dynamic COMMENT = "运营操作日志表";
-- tian-gong.sys_platform_stats_daily DDL
CREATE TABLE `tian-gong`.`sys_platform_stats_daily` (`id` INT NOT NULL AUTO_INCREMENT Comment "ID",
`stat_date` INT NOT NULL Comment "统计日期（YYYYMMDD）",
`new_user_count` INT NOT NULL DEFAULT 0 Comment "新增用户数",
`active_user_count` INT NOT NULL DEFAULT 0 Comment "活跃用户数",
`total_recharge` DECIMAL(20,2) NOT NULL DEFAULT 0.00 Comment "充值总金额",
`recharge_count` INT NOT NULL DEFAULT 0 Comment "充值订单数",
`total_withdraw` DECIMAL(20,2) NOT NULL DEFAULT 0.00 Comment "提现总金额",
`withdraw_count` INT NOT NULL DEFAULT 0 Comment "提现订单数",
`total_bet` DECIMAL(20,2) NOT NULL DEFAULT 0.00 Comment "下注总金额",
`bet_count` INT NOT NULL DEFAULT 0 Comment "下注订单数",
`total_win` DECIMAL(20,2) NOT NULL DEFAULT 0.00 Comment "派奖总金额",
`platform_profit` DECIMAL(20,2) NOT NULL DEFAULT 0.00 Comment "平台盈利",
`vip_bonus` DECIMAL(20,2) NOT NULL DEFAULT 0.00 Comment "VIP 发放礼金",
`activity_reward` DECIMAL(20,2) NOT NULL DEFAULT 0.00 Comment "活动奖励",
`create_time` BIGINT NOT NULL Comment "创建时间（毫秒）",
`is_deleted` TINYINT(1) NULL DEFAULT 0,
`created_at` BIGINT NULL,
`updated_at` BIGINT NULL,
`created_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
`updated_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
INDEX `idx_create_time`(`create_time` ASC) USING BTREE,
UNIQUE INDEX `uk_stat_date`(`stat_date` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 1 ROW_FORMAT = Dynamic COMMENT = "平台每日统计表";
-- tian-gong.system_metric DDL
CREATE TABLE `tian-gong`.`system_metric` (`id` BIGINT NOT NULL AUTO_INCREMENT Comment "指标 ID",
`metric_type` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "指标类型（cpu/memory/disk/network）",
`metric_name` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "指标名称",
`metric_value` DECIMAL(10,2) NOT NULL Comment "指标值",
`unit` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "单位",
`service_name` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "服务名称",
`recorded_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP Comment "记录时间",
INDEX `idx_recorded_at`(`recorded_at` ASC) USING BTREE,
INDEX `idx_type`(`metric_type` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 1 ROW_FORMAT = Dynamic COMMENT = "系统指标表";
-- tian-gong.usr_2fa DDL
CREATE TABLE `tian-gong`.`usr_2fa` (`id` BIGINT NOT NULL AUTO_INCREMENT,
`secret` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "2FA密钥",
`is_enabled` INT NULL DEFAULT 0 Comment "是否启用：0-禁用，1-启用",
`backup_codes` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "备用码(逗号分隔)",
`create_time` BIGINT NULL Comment "创建时间(毫秒)",
`modify_time` BIGINT NULL Comment "修改时间(毫秒)",
`is_deleted` TINYINT(1) NULL DEFAULT 0,
`created_at` BIGINT NULL,
`updated_at` BIGINT NULL,
`created_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
`updated_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
`uid` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "用户 UID",
INDEX `idx_uid`(`uid` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 4 ROW_FORMAT = Dynamic COMMENT = "用户2FA表";
-- tian-gong.usr_account DDL
CREATE TABLE `tian-gong`.`usr_account` (`id` BIGINT NOT NULL AUTO_INCREMENT,
`uid` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "用户 UID",
`balance` DECIMAL(20,2) NULL DEFAULT 0.00 Comment "余额 (分)",
`frozen_balance` DECIMAL(20,2) NULL DEFAULT 0.00 Comment "冻结余额",
`total_bet` DECIMAL(20,2) NULL DEFAULT 0.00 Comment "累计下注",
`total_win` DECIMAL(20,2) NULL DEFAULT 0.00 Comment "累计赢利",
`total_recharge` DECIMAL(20,2) NULL DEFAULT 0.00 Comment "累计充值",
`total_withdraw` DECIMAL(20,2) NULL DEFAULT 0.00 Comment "累计提现",
`is_deleted` TINYINT(1) NULL DEFAULT 0,
`created_at` BIGINT NULL,
`updated_at` BIGINT NULL,
`created_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
`updated_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
`locking_amount` BIGINT NULL,
`today_recharge_amount` DECIMAL(20,2) NULL,
UNIQUE INDEX `uk_uid`(`uid` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 1346 ROW_FORMAT = Dynamic COMMENT = "用户账户表";
-- tian-gong.usr_account_flow DDL
CREATE TABLE `tian-gong`.`usr_account_flow` (`id` BIGINT NOT NULL AUTO_INCREMENT Comment "主键ID",
`uid` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "用户ID",
`type` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "变动类型",
`amount` DECIMAL(20,8) NOT NULL DEFAULT 0.00000000 Comment "变动金额（分）",
`balance_before` DECIMAL(20,8) NOT NULL DEFAULT 0.00000000 Comment "变动前余额（分）",
`balance_after` DECIMAL(20,8) NOT NULL DEFAULT 0.00000000 Comment "变动后余额（分）",
`frozen_before` DECIMAL(20,8) NOT NULL DEFAULT 0.00000000 Comment "变动前冻结金额（分）",
`frozen_after` DECIMAL(20,8) NOT NULL DEFAULT 0.00000000 Comment "变动后冻结金额（分）",
`order_no` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "相关订单号",
`remark` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "备注",
`created_at` BIGINT NOT NULL DEFAULT 0 Comment "创建时间",
`updated_at` BIGINT NOT NULL DEFAULT 0 Comment "更新时间",
`created_by` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "创建人",
`updated_by` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "更新人",
`is_deleted` TINYINT NOT NULL DEFAULT 0 Comment "是否删除",
INDEX `idx_created_at`(`created_at` ASC) USING BTREE,
INDEX `idx_order_no`(`order_no` ASC) USING BTREE,
INDEX `idx_type`(`type` ASC) USING BTREE,
INDEX `idx_uid`(`uid` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 68 ROW_FORMAT = Dynamic COMMENT = "用户账户流水表";
-- tian-gong.usr_bank_account DDL
CREATE TABLE `tian-gong`.`usr_bank_account` (`id` BIGINT NOT NULL AUTO_INCREMENT Comment "主键ID",
`uid` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL Comment "用户UID",
`account_name` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL Comment "账户持有人姓名",
`bank_code` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL Comment "银行/渠道代码（如gcash、paymaya）",
`bank_name` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "银行/渠道名称",
`account_number` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL Comment "账号",
`is_default` INT NULL DEFAULT 0 Comment "是否默认账户：0-否，1-是",
`status` INT NULL DEFAULT 1 Comment "状态：0-禁用，1-启用",
`created_at` BIGINT NOT NULL Comment "创建时间（毫秒）",
`updated_at` BIGINT NOT NULL Comment "更新时间（毫秒）",
`is_deleted` INT NULL DEFAULT 0 Comment "逻辑删除：0-未删除，1-已删除",
`created_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
`updated_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
INDEX `idx_status`(`status` ASC) USING BTREE,
INDEX `idx_uid`(`uid` ASC) USING BTREE,
INDEX `uk_uid_account`(`uid` ASC,`account_number` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci AUTO_INCREMENT = 12 ROW_FORMAT = Dynamic COMMENT = "用户收款账户表";
-- tian-gong.usr_flow_requirement DDL
CREATE TABLE `tian-gong`.`usr_flow_requirement` (`id` BIGINT NOT NULL AUTO_INCREMENT,
`uid` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "用户 UID",
`recharge_amount` DECIMAL(20,2) NOT NULL Comment "充值金额",
`required_flow` DECIMAL(20,2) NOT NULL Comment "要求流水",
`completed_flow` DECIMAL(20,2) NULL DEFAULT 0.00 Comment "已完成流水",
`status` INT NULL DEFAULT 0 Comment "状态：0-进行中，1-完成，2-豁免",
`is_deleted` TINYINT(1) NULL DEFAULT 0,
`created_at` BIGINT NULL,
`updated_at` BIGINT NULL,
`created_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
`updated_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
`source` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
`trigger_reason` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
`flow_multiple` INT NULL,
`activity_bonus` INT NULL,
`activity_flow` INT NULL,
`completed_at` BIGINT NULL,
`expire_time` BIGINT NULL,
INDEX `idx_uid`(`uid` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 16 ROW_FORMAT = Dynamic COMMENT = "流水要求表";
-- tian-gong.usr_invite_device_blacklist DDL
CREATE TABLE `tian-gong`.`usr_invite_device_blacklist` (`id` BIGINT NOT NULL AUTO_INCREMENT Comment "主键 ID",
`device_fingerprint` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "设备指纹",
`reason` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "加入黑名单原因",
`status` TINYINT NOT NULL DEFAULT 1 Comment "状态 (1:禁用，0:启用)",
`expire_time` BIGINT NULL Comment "过期时间 (毫秒)",
`created_at` BIGINT NOT NULL Comment "创建时间 (毫秒)",
`updated_at` BIGINT NOT NULL Comment "更新时间 (毫秒)",
`is_deleted` TINYINT NOT NULL DEFAULT 0 Comment "软删除",
`created_by` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "创建人",
`updated_by` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "更新人",
INDEX `idx_status`(`status` ASC) USING BTREE,
UNIQUE INDEX `uk_device`(`device_fingerprint` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 2 ROW_FORMAT = Dynamic COMMENT = "设备指纹黑名单表";
-- tian-gong.usr_invite_rank_reward DDL
CREATE TABLE `tian-gong`.`usr_invite_rank_reward` (`id` BIGINT NOT NULL AUTO_INCREMENT Comment "主键ID",
`rank_type` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL Comment "排行榜类型：DAILY, WEEKLY, MONTHLY",
`rank_position` INT NOT NULL Comment "名次：1, 2, 3",
`reward_amount` DECIMAL(18,2) NOT NULL Comment "奖励金额",
`status` INT NULL DEFAULT 1 Comment "状态：0-禁用，1-启用",
`created_at` BIGINT NOT NULL Comment "创建时间（毫秒）",
`updated_at` BIGINT NOT NULL Comment "更新时间（毫秒）",
`is_deleted` INT NULL DEFAULT 0 Comment "逻辑删除：0-未删除，1-已删除",
`created_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
`updated_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
INDEX `idx_status`(`status` ASC) USING BTREE,
UNIQUE INDEX `uk_type_position`(`rank_type` ASC,`rank_position` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci AUTO_INCREMENT = 10 ROW_FORMAT = Dynamic COMMENT = "排行榜奖励配置表";
-- tian-gong.usr_invite_rebate_config DDL
CREATE TABLE `tian-gong`.`usr_invite_rebate_config` (`id` BIGINT NOT NULL AUTO_INCREMENT Comment "主键 ID",
`config_type` TINYINT NOT NULL Comment "配置类型 (1:首充返利，2:流水分成)",
`vip_level` TINYINT NOT NULL DEFAULT 0 Comment "VIP 等级 (0 为通用)",
`min_amount` DECIMAL(12,2) NULL Comment "最低金额门槛",
`max_amount` DECIMAL(12,2) NULL Comment "最高金额门槛",
`rebate_type` TINYINT NOT NULL Comment "返利类型 (1:固定金额，2:比例，3:阶梯)",
`rebate_value` DECIMAL(12,2) NOT NULL Comment "返利值 (金额或比例)",
`daily_limit` DECIMAL(12,2) NULL DEFAULT 0.00 Comment "每日上限",
`monthly_limit` DECIMAL(12,2) NULL DEFAULT 0.00 Comment "每月上限",
`status` TINYINT NOT NULL DEFAULT 1 Comment "状态 (1:启用，0:禁用)",
`sort_order` INT NOT NULL DEFAULT 0 Comment "排序",
`remark` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "备注",
`created_at` BIGINT NOT NULL Comment "创建时间 (毫秒)",
`updated_at` BIGINT NOT NULL Comment "更新时间 (毫秒)",
`is_deleted` TINYINT NOT NULL DEFAULT 0 Comment "软删除",
`created_by` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "创建人",
`updated_by` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "更新人",
INDEX `idx_config_type`(`config_type` ASC) USING BTREE,
INDEX `idx_status`(`status` ASC) USING BTREE,
INDEX `idx_vip_level`(`vip_level` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 19 ROW_FORMAT = Dynamic COMMENT = "邀请返利配置表";
-- tian-gong.usr_invite_rebates DDL
CREATE TABLE `tian-gong`.`usr_invite_rebates` (`id` BIGINT NOT NULL AUTO_INCREMENT Comment "主键 ID",
`invite_id` BIGINT NOT NULL Comment "邀请关系 ID",
`source_id` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "来源 ID(充值订单号/流水 ID)",
`rebate_type` TINYINT NOT NULL Comment "类型 (1:首充返利，2:流水分成，3:排行榜奖励)",
`base_amount` DECIMAL(12,2) NOT NULL Comment "基础金额",
`rate` DECIMAL(5,4) NOT NULL Comment "返利比例",
`amount` DECIMAL(12,2) NOT NULL Comment "返利金额",
`status` TINYINT NOT NULL DEFAULT 0 Comment "状态 (0:pending, 1:paid, 2:frozen, 3:cancelled)",
`pay_time` BIGINT NULL Comment "发放时间 (毫秒)",
`remark` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "备注",
`created_at` BIGINT NOT NULL Comment "创建时间 (毫秒)",
`updated_at` BIGINT NOT NULL Comment "更新时间 (毫秒)",
`is_deleted` TINYINT NOT NULL DEFAULT 0 Comment "软删除",
`created_by` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "创建人",
`updated_by` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "更新人",
`inviter_uid` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "邀请人 UID",
`invitee_uid` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "被邀请人 UID",
INDEX `idx_created`(`created_at` ASC) USING BTREE,
INDEX `idx_invitee_uid`(`invitee_uid` ASC) USING BTREE,
INDEX `idx_inviter_uid`(`inviter_uid` ASC) USING BTREE,
INDEX `idx_status`(`status` ASC) USING BTREE,
UNIQUE INDEX `uk_invite_source`(`invite_id` ASC,`source_id` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 1 ROW_FORMAT = Dynamic COMMENT = "返利记录表";
-- tian-gong.usr_invite_relations DDL
CREATE TABLE `tian-gong`.`usr_invite_relations` (`id` BIGINT NOT NULL AUTO_INCREMENT Comment "主键 ID",
`invite_code` VARCHAR(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "邀请码",
`bind_time` BIGINT NOT NULL Comment "绑定时间 (毫秒)",
`bind_source` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "绑定来源",
`device_fingerprint` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "设备指纹",
`ip_address` VARCHAR(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "IP 地址",
`status` TINYINT NOT NULL DEFAULT 1 Comment "状态 (1:active, 0:frozen, -1:invalid)",
`created_at` BIGINT NOT NULL Comment "创建时间 (毫秒)",
`updated_at` BIGINT NOT NULL Comment "更新时间 (毫秒)",
`is_deleted` TINYINT NOT NULL DEFAULT 0 Comment "软删除",
`created_by` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "创建人",
`updated_by` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "更新人",
`inviter_uid` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "邀请人 UID",
`invitee_uid` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "被邀请人 UID",
INDEX `idx_invite_code`(`invite_code` ASC) USING BTREE,
INDEX `idx_invitee_uid`(`invitee_uid` ASC) USING BTREE,
INDEX `idx_inviter_uid`(`inviter_uid` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 3 ROW_FORMAT = Dynamic COMMENT = "邀请关系表";
-- tian-gong.usr_invite_stats_daily DDL
CREATE TABLE `tian-gong`.`usr_invite_stats_daily` (`id` BIGINT NOT NULL AUTO_INCREMENT Comment "主键 ID",
`stat_date` DATE NOT NULL Comment "统计日期",
`new_invitees` INT NOT NULL DEFAULT 0 Comment "新增邀请人数",
`valid_invitees` INT NOT NULL DEFAULT 0 Comment "有效邀请人数",
`total_rebate` DECIMAL(12,2) NOT NULL DEFAULT 0.00 Comment "返利总额",
`first_deposit_rebate` DECIMAL(12,2) NOT NULL DEFAULT 0.00 Comment "首充返利",
`revenue_share_rebate` DECIMAL(12,2) NOT NULL DEFAULT 0.00 Comment "流水分成",
`rank_bonus` DECIMAL(12,2) NOT NULL DEFAULT 0.00 Comment "排行榜奖励",
`created_at` BIGINT NOT NULL Comment "创建时间 (毫秒)",
`updated_at` BIGINT NOT NULL Comment "更新时间 (毫秒)",
`is_deleted` TINYINT NOT NULL DEFAULT 0 Comment "软删除",
`created_by` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "创建人",
`updated_by` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "更新人",
`inviter_uid` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "邀请人 UID",
INDEX `idx_inviter_uid`(`inviter_uid` ASC) USING BTREE,
INDEX `idx_stat_date`(`stat_date` ASC) USING BTREE,
UNIQUE INDEX `uk_date_inviter`(`stat_date` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 1 ROW_FORMAT = Dynamic COMMENT = "邀请统计表";
-- tian-gong.usr_role DDL
CREATE TABLE `tian-gong`.`usr_role` (`id` BIGINT NOT NULL AUTO_INCREMENT,
`role_id` BIGINT NOT NULL Comment "角色 ID",
`create_at` BIGINT NOT NULL Comment "创建时间",
`create_by` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "创建人",
`is_deleted` TINYINT(1) NULL DEFAULT 0,
`created_at` BIGINT NULL,
`updated_at` BIGINT NULL,
`created_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
`updated_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
`uid` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "用户 UID",
INDEX `idx_role_id`(`role_id` ASC) USING BTREE,
INDEX `idx_uid`(`uid` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 1 ROW_FORMAT = Dynamic COMMENT = "用户角色关联表";
-- tian-gong.usr_user DDL
CREATE TABLE `tian-gong`.`usr_user` (`id` BIGINT NOT NULL AUTO_INCREMENT Comment "用户 ID",
`uid` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "用户唯一标识",
`username` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "用户名",
`password` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "密码 (BCrypt)",
`email` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "邮箱",
`phone` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "手机号",
`avatar` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "头像",
`birthday` DATE NULL Comment "生日",
`vip_level` INT NULL DEFAULT 0 Comment "VIP 等级",
`risk_level` INT NULL DEFAULT 0 Comment "风险等级",
`invite_code` VARCHAR(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "用户邀请码",
`referral_code` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "推荐我玩的人的邀请码",
`has_first_deposit` TINYINT NOT NULL DEFAULT 0 Comment "是否已完成首充 (0:否，1:是)",
`status` INT NULL DEFAULT 1 Comment "状态：0-禁用，1-正常",
`is_deleted` TINYINT(1) NULL DEFAULT 0,
`created_at` BIGINT NULL,
`updated_at` BIGINT NULL,
`created_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
`updated_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
`last_login_time` BIGINT NULL,
INDEX `idx_status`(`status` ASC) USING BTREE,
UNIQUE INDEX `uk_invite_code`(`invite_code` ASC) USING BTREE,
UNIQUE INDEX `uk_uid`(`uid` ASC) USING BTREE,
UNIQUE INDEX `uk_username`(`username` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 1369 ROW_FORMAT = Dynamic COMMENT = "用户表";
-- tian-gong.usr_user_group DDL
CREATE TABLE `tian-gong`.`usr_user_group` (`id` BIGINT NOT NULL AUTO_INCREMENT Comment "分组ID",
`name` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL Comment "分组名称",
`code` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL Comment "分组代码（唯一标识）",
`description` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "分组描述",
`color` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '#2ecc71' Comment "分组颜色（用于前端展示）",
`icon` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "分组图标",
`sort_order` INT NULL DEFAULT 0 Comment "排序权重",
`status` TINYINT NOT NULL DEFAULT 1 Comment "状态：0-禁用，1-启用",
`user_count` INT NULL DEFAULT 0 Comment "关联用户数量（缓存）",
`created_by` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "创建人",
`is_deleted` TINYINT(1) NULL DEFAULT 0 Comment "是否删除",
`created_at` BIGINT NULL Comment "创建时间（毫秒时间戳）",
`updated_at` BIGINT NULL Comment "更新时间（毫秒时间戳）",
`updated_by` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "更新人",
INDEX `idx_sort_order`(`sort_order` ASC) USING BTREE,
INDEX `idx_status`(`status` ASC) USING BTREE,
UNIQUE INDEX `uk_code`(`code` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci AUTO_INCREMENT = 8 ROW_FORMAT = Dynamic COMMENT = "用户分组表";
-- tian-gong.usr_user_group_relation DDL
CREATE TABLE `tian-gong`.`usr_user_group_relation` (`id` BIGINT NOT NULL AUTO_INCREMENT Comment "关联ID",
`uid` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL Comment "用户UID",
`group_id` BIGINT NOT NULL Comment "分组ID",
`relation_time` BIGINT NULL Comment "关联时间（毫秒时间戳）",
`operator_id` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "关联操作人",
`remark` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "备注",
`is_deleted` TINYINT(1) NULL DEFAULT 0 Comment "是否删除",
`created_at` BIGINT NULL Comment "创建时间（毫秒时间戳）",
`updated_at` BIGINT NULL Comment "更新时间（毫秒时间戳）",
`created_by` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "创建人",
`updated_by` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "更新人",
INDEX `idx_group_id`(`group_id` ASC) USING BTREE,
INDEX `idx_uid`(`uid` ASC) USING BTREE,
UNIQUE INDEX `uk_uid_group`(`uid` ASC,`group_id` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci AUTO_INCREMENT = 1 ROW_FORMAT = Dynamic COMMENT = "用户分组关联表";
-- tian-gong.usr_user_tag DDL
CREATE TABLE `tian-gong`.`usr_user_tag` (`id` BIGINT NOT NULL AUTO_INCREMENT Comment "标签ID",
`name` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL Comment "标签名称",
`code` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL Comment "标签代码（唯一标识）",
`tag_type` TINYINT NOT NULL DEFAULT 1 Comment "标签类型：1-系统自动标签，2-手动标签",
`category` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "标签分类（用于分组展示）",
`color` VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT '#3498db' Comment "标签颜色（用于前端展示）",
`icon` VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "标签图标",
`description` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "标签描述",
`auto_rule` VARCHAR(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "自动标签规则（JSON格式）",
`sort_order` INT NULL DEFAULT 0 Comment "排序权重",
`status` TINYINT NOT NULL DEFAULT 1 Comment "状态：0-禁用，1-启用",
`user_count` INT NULL DEFAULT 0 Comment "关联用户数量（缓存）",
`is_deleted` TINYINT(1) NULL DEFAULT 0 Comment "是否删除",
`created_at` BIGINT NULL Comment "创建时间（毫秒时间戳）",
`updated_at` BIGINT NULL Comment "更新时间（毫秒时间戳）",
`created_by` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "创建人",
`updated_by` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "更新人",
INDEX `idx_category`(`category` ASC) USING BTREE,
INDEX `idx_sort_order`(`sort_order` ASC) USING BTREE,
INDEX `idx_status`(`status` ASC) USING BTREE,
INDEX `idx_tag_type`(`tag_type` ASC) USING BTREE,
UNIQUE INDEX `uk_code`(`code` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci AUTO_INCREMENT = 20 ROW_FORMAT = Dynamic COMMENT = "用户标签表";
-- tian-gong.usr_user_tag_relation DDL
CREATE TABLE `tian-gong`.`usr_user_tag_relation` (`id` BIGINT NOT NULL AUTO_INCREMENT Comment "关联ID",
`uid` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL Comment "用户UID",
`tag_id` BIGINT NOT NULL Comment "标签ID",
`relation_type` TINYINT NOT NULL DEFAULT 2 Comment "关联类型：1-系统自动关联，2-手动关联",
`relation_time` BIGINT NULL Comment "关联时间（毫秒时间戳）",
`operator_id` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "关联操作人（手动关联时记录）",
`remark` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "备注",
`is_deleted` TINYINT(1) NULL DEFAULT 0 Comment "是否删除",
`created_at` BIGINT NULL Comment "创建时间（毫秒时间戳）",
`updated_at` BIGINT NULL Comment "更新时间（毫秒时间戳）",
`created_by` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "创建人",
`updated_by` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL Comment "更新人",
INDEX `idx_relation_type`(`relation_type` ASC) USING BTREE,
INDEX `idx_tag_id`(`tag_id` ASC) USING BTREE,
INDEX `idx_uid`(`uid` ASC) USING BTREE,
UNIQUE INDEX `uk_uid_tag`(`uid` ASC,`tag_id` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci AUTO_INCREMENT = 1 ROW_FORMAT = Dynamic COMMENT = "用户标签关联表";
-- tian-gong.usr_user_vip DDL
CREATE TABLE `tian-gong`.`usr_user_vip` (`id` INT NOT NULL AUTO_INCREMENT Comment "ID",
`uid` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "用户 ID",
`vip_level` INT NOT NULL DEFAULT 1 Comment "当前 VIP 等级",
`exp` INT NOT NULL DEFAULT 0 Comment "VIP 经验",
`total_growth` BIGINT NOT NULL DEFAULT 0 Comment "总成长值",
`cycle_growth` INT NOT NULL DEFAULT 0 Comment "周期成长值",
`cycle_start` BIGINT NULL Comment "保级周期开始时间（毫秒）",
`cycle_end` BIGINT NULL Comment "保级周期结束时间（毫秒）",
`last_upgrade_time` BIGINT NULL Comment "上次升级时间（毫秒）",
`last_downgrade_time` BIGINT NULL Comment "上次降级时间（毫秒）",
`highest_level` TINYINT NOT NULL DEFAULT 0 Comment "历史最高等级",
`status` TINYINT NOT NULL DEFAULT 1 Comment "状态 (1 正常 2 冻结 3 降级中)",
`total_recharge` DECIMAL(20,2) NOT NULL DEFAULT 0.00 Comment "累计充值金额",
`total_bet` DECIMAL(20,2) NOT NULL DEFAULT 0.00 Comment "累计下注金额",
`claimed_rebate` DECIMAL(20,2) NOT NULL DEFAULT 0.00 Comment "已领取返利金额",
`claimed_bonus` DECIMAL(20,2) NOT NULL DEFAULT 0.00 Comment "已领取礼金金额",
`last_bonus_time` BIGINT NULL Comment "上次领取礼金时间（毫秒）",
`is_deleted` TINYINT(1) NULL DEFAULT 0,
`created_at` BIGINT NULL,
`updated_at` BIGINT NULL,
`created_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
`updated_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
`claimed_bet_base` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
INDEX `idx_vip_level`(`vip_level` ASC) USING BTREE,
UNIQUE INDEX `uk_uid`(`uid` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 22 ROW_FORMAT = Dynamic COMMENT = "用户 VIP 信息表";
-- tian-gong.usr_vip_gift DDL
CREATE TABLE `tian-gong`.`usr_vip_gift` (`id` BIGINT NOT NULL AUTO_INCREMENT,
`gift_type` TINYINT NOT NULL Comment "类型 (1 升级礼包 2 生日礼包 3 回归礼包)",
`vip_level` TINYINT NOT NULL Comment "VIP 等级",
`gift_name` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "礼包名称",
`gift_value` DECIMAL(10,2) NOT NULL Comment "礼包价值",
`gift_content` JSON NOT NULL Comment "礼包内容",
`claim_condition` JSON NULL Comment "领取条件",
`status` TINYINT NOT NULL DEFAULT 1 Comment "状态 (1 启用 0 禁用)",
`created_at` BIGINT NOT NULL Comment "创建时间（毫秒）",
`updated_at` BIGINT NOT NULL Comment "更新时间（毫秒）",
`is_deleted` TINYINT NOT NULL DEFAULT 0 Comment "是否删除 (0-否 1-是)",
`created_by` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "创建人",
`updated_by` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "更新人",
INDEX `idx_type_level`(`gift_type` ASC,`vip_level` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 36 ROW_FORMAT = Dynamic COMMENT = "VIP 礼包表";
-- tian-gong.usr_vip_gift_record DDL
CREATE TABLE `tian-gong`.`usr_vip_gift_record` (`id` BIGINT NOT NULL AUTO_INCREMENT,
`uid` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "用户 ID",
`gift_id` BIGINT NOT NULL Comment "礼包 ID",
`gift_type` TINYINT NOT NULL Comment "类型 (1 升级礼包 2 生日礼包 3 回归礼包)",
`claim_time` BIGINT NOT NULL Comment "领取时间（毫秒）",
`claim_value` DECIMAL(10,2) NULL Comment "领取价值",
`status` TINYINT NOT NULL DEFAULT 1 Comment "状态 (1 已领取 2 已发放 3 已使用)",
`created_at` BIGINT NOT NULL Comment "创建时间（毫秒）",
`updated_at` BIGINT NOT NULL Comment "更新时间（毫秒）",
`is_deleted` TINYINT NOT NULL DEFAULT 0 Comment "是否删除 (0-否 1-是)",
`created_by` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "创建人",
`updated_by` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "更新人",
INDEX `idx_claim_time`(`claim_time` ASC) USING BTREE,
INDEX `idx_gift_id`(`gift_id` ASC) USING BTREE,
INDEX `idx_uid`(`uid` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 1 ROW_FORMAT = Dynamic COMMENT = "用户礼包领取记录表";
-- tian-gong.usr_vip_growth_record DDL
CREATE TABLE `tian-gong`.`usr_vip_growth_record` (`id` BIGINT NOT NULL AUTO_INCREMENT Comment "主键 ID",
`uid` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "用户 ID",
`type` TINYINT NOT NULL Comment "类型 (1 充值 2 投注 3 签到 4 任务 5 活动 6 邀请)",
`amount` INT NOT NULL Comment "成长值金额",
`balance` BIGINT NOT NULL Comment "变更后余额",
`expire_time` BIGINT NULL Comment "过期时间（毫秒）",
`source_id` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "来源 ID(订单 ID/任务 ID 等)",
`source_desc` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "来源描述",
`status` TINYINT NOT NULL DEFAULT 1 Comment "状态 (1 有效 2 过期 3 撤销)",
`created_at` BIGINT NOT NULL Comment "创建时间（毫秒）",
`updated_at` BIGINT NOT NULL Comment "更新时间（毫秒）",
`is_deleted` TINYINT NOT NULL DEFAULT 0 Comment "是否删除 (0-否 1-是)",
`created_by` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "创建人",
`updated_by` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "更新人",
INDEX `idx_created_at`(`created_at` ASC) USING BTREE,
INDEX `idx_expire_time`(`expire_time` ASC) USING BTREE,
INDEX `idx_type`(`type` ASC) USING BTREE,
INDEX `idx_uid`(`uid` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 424793 ROW_FORMAT = Dynamic COMMENT = "成长值流水表";
-- tian-gong.usr_vip_level DDL
CREATE TABLE `tian-gong`.`usr_vip_level` (`id` INT NOT NULL AUTO_INCREMENT Comment "ID",
`level` INT NOT NULL Comment "VIP等级(1-10)",
`name` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "VIP名称",
`required_exp` INT NOT NULL DEFAULT 0 Comment "升级所需经验",
`cycle_growth_required` INT NOT NULL DEFAULT 0 Comment "保级周期成长值要求",
`cycle_days` INT NOT NULL DEFAULT 30 Comment "保级周期天数",
`rebate_rate` DECIMAL(5,2) NULL DEFAULT 0.00 Comment "升级返利比例",
`weekly_bonus` DECIMAL(20,2) NULL DEFAULT 0.00 Comment "每周礼金",
`birthday_bonus` DECIMAL(20,2) NULL DEFAULT 0.00 Comment "生日礼金",
`daily_rebate_limit` DECIMAL(10,2) NOT NULL DEFAULT 0.00 Comment "每日返水上限（元）",
`return_gift_value` DECIMAL(10,2) NOT NULL DEFAULT 0.00 Comment "回归礼包价值（元）",
`has_dedicated_service` INT NULL DEFAULT 0 Comment "专属客服(0/1)",
`has_priority_withdraw` INT NULL DEFAULT 0 Comment "提现优先(0/1)",
`status` INT NULL DEFAULT 1 Comment "状态(0-下架, 1-上架)",
`remark` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "备注",
`is_deleted` TINYINT(1) NULL DEFAULT 0,
`created_at` BIGINT NULL,
`updated_at` BIGINT NULL,
`created_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
`updated_by` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
`has_priority_with` INT NULL,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 8 ROW_FORMAT = Dynamic COMMENT = "VIP等级配置";
-- tian-gong.usr_vip_level_privilege DDL
CREATE TABLE `tian-gong`.`usr_vip_level_privilege` (`id` BIGINT NOT NULL AUTO_INCREMENT,
`vip_level` TINYINT NOT NULL Comment "VIP 等级",
`privilege_id` BIGINT NOT NULL Comment "权益 ID",
`config` JSON NULL Comment "权益配置 (如返利比例等)",
`daily_limit` INT NULL Comment "每日使用次数限制",
`monthly_limit` INT NULL Comment "每月使用次数限制",
`total_limit` INT NULL Comment "总使用次数限制",
`status` TINYINT NOT NULL DEFAULT 1 Comment "状态 (1 启用 0 禁用)",
`created_at` BIGINT NOT NULL Comment "创建时间（毫秒）",
`updated_at` BIGINT NOT NULL Comment "更新时间（毫秒）",
`is_deleted` TINYINT NOT NULL DEFAULT 0 Comment "是否删除 (0-否 1-是)",
`created_by` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "创建人",
`updated_by` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "更新人",
INDEX `idx_privilege_id`(`privilege_id` ASC) USING BTREE,
UNIQUE INDEX `uk_level_privilege`(`vip_level` ASC,`privilege_id` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 61 ROW_FORMAT = Dynamic COMMENT = "VIP 等级权益关联表";
-- tian-gong.usr_vip_privilege DDL
CREATE TABLE `tian-gong`.`usr_vip_privilege` (`id` BIGINT NOT NULL AUTO_INCREMENT,
`privilege_code` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "权益代码",
`privilege_name` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "权益名称",
`privilege_type` TINYINT NOT NULL Comment "类型 (1 返利 2 服务 3 活动 4 礼包 5 其他)",
`description` VARCHAR(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "权益描述",
`icon` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "图标 URL",
`sort_order` INT NOT NULL DEFAULT 0 Comment "排序",
`status` TINYINT NOT NULL DEFAULT 1 Comment "状态 (1 启用 0 禁用)",
`created_at` BIGINT NOT NULL Comment "创建时间（毫秒）",
`updated_at` BIGINT NOT NULL Comment "更新时间（毫秒）",
`is_deleted` TINYINT NOT NULL DEFAULT 0 Comment "是否删除 (0-否 1-是)",
`created_by` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "创建人",
`updated_by` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "更新人",
UNIQUE INDEX `uk_code`(`privilege_code` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 20 ROW_FORMAT = Dynamic COMMENT = "VIP 权益配置表";
-- tian-gong.usr_vip_privilege_usage DDL
CREATE TABLE `tian-gong`.`usr_vip_privilege_usage` (`id` BIGINT NOT NULL AUTO_INCREMENT,
`uid` VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL Comment "用户 ID",
`privilege_id` BIGINT NOT NULL Comment "权益 ID",
`usage_time` BIGINT NOT NULL Comment "使用时间（毫秒）",
`usage_value` DECIMAL(10,2) NULL Comment "使用数值 (如返利金额)",
`source_id` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "来源 ID",
`source_desc` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "来源描述",
`status` TINYINT NOT NULL DEFAULT 1 Comment "状态 (1 成功 2 失败)",
`remark` VARCHAR(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "备注",
`created_at` BIGINT NOT NULL Comment "创建时间（毫秒）",
`updated_at` BIGINT NOT NULL Comment "更新时间（毫秒）",
`is_deleted` TINYINT NOT NULL DEFAULT 0 Comment "是否删除 (0-否 1-是)",
`created_by` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "创建人",
`updated_by` VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL Comment "更新人",
INDEX `idx_privilege_id`(`privilege_id` ASC) USING BTREE,
INDEX `idx_uid`(`uid` ASC) USING BTREE,
INDEX `idx_usage_time`(`usage_time` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci AUTO_INCREMENT = 1 ROW_FORMAT = Dynamic COMMENT = "权益使用记录表";
-- tian-gong.usr_vip_rebate_record DDL
CREATE TABLE `tian-gong`.`usr_vip_rebate_record` (`id` BIGINT NOT NULL AUTO_INCREMENT Comment "主键ID",
`uid` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL Comment "用户UID",
`vip_level` INT NOT NULL Comment "领取时的VIP等级",
`bet_amount` DECIMAL(18,2) NOT NULL Comment "累计投注金额",
`rebate_rate` DECIMAL(5,2) NOT NULL Comment "返利比例",
`rebate_amount` DECIMAL(18,2) NOT NULL Comment "返利金额",
`period_start` BIGINT NOT NULL Comment "统计周期开始时间",
`period_end` BIGINT NOT NULL Comment "统计周期结束时间",
`status` INT NOT NULL DEFAULT 1 Comment "状态：0-待发放，1-已发放，2-已取消",
`claimed_at` BIGINT NULL Comment "领取时间",
`created_at` BIGINT NOT NULL Comment "创建时间",
`updated_at` BIGINT NOT NULL Comment "更新时间",
INDEX `idx_period`(`period_start` ASC,`period_end` ASC) USING BTREE,
INDEX `idx_status`(`status` ASC) USING BTREE,
INDEX `idx_uid`(`uid` ASC) USING BTREE,
PRIMARY KEY (`id`)) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci AUTO_INCREMENT = 1 ROW_FORMAT = Dynamic COMMENT = "VIP返利记录表";
SET FOREIGN_KEY_CHECKS = 1;
